name: snapd-restapi
version: '1'
summary: Use snapd rest api
description: |
  Use the snapd rest api

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  install:
    command: install
    plugs: [snapd-control, network]
  daemon:
    daemon: simple
    command: daemon
    plugs: [snapd-control]

parts:
  go:
    plugin: go
    source: . 
    go-importpath: github.com/knitzsche/restclient
    stage:
      - -bin/install
  cmds:
    plugin: go
    source: .
    go-importpath: github.com/knitzsche/install
    stage:
      - -bin/restclient
      - -bin/daemon
