name: snapd-restapi
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Use snapd rest api
description: |
  Use the snapd rest api

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  daemon:
    command: daemon
    plugs: [snapd-control]

parts:
  go:
    plugin: go
    source: . 
    go-importpath: github.com/knitzsche/restclient
